name: ClockHash Security Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Flask App Requirements
        run: |
          pip install flask
          python app/main.py &       # Run app in background
          sleep 5                    # Give it a few seconds to start

      - name: Run ClockHash Scan
        uses: your-username/clockhash-scan@main
        with:
          target: "."
          url: "http://localhost:3000"

      - name: Upload Scan Reports
        uses: actions/upload-artifact@v4
        with:
          name: clockhash-reports
          path: reports/
